### ISSUE TITLE
I cannot transfer token

### ISSUE THREAD

**Issue by btcre** [generEOS/eostoolkit#11]
I tried to transfer KARMA token by changing the Symbol KARMA but I'm getting Transaction failed, Is there a way to transfer token?

**Comment by Khazius** [comment]
Fixed

**Comment by btcre** [comment]
Still failed
Transaction failed. [3050003] eosio_assert_message_exception: eosio_assert_message assertion failure. assertion failure with message: unable to find key
